Controllers/SupplierRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel.SupplierRegistration;
using static WrokFlowWeb.Constants.Constants;

namespace WrokFlowWeb.Controllers
{
    public class SupplierRegistrationController : Controller
    {

        private readonly ISupplierRegistrationService supplierRegistrationService;

        public SupplierRegistrationController(ISupplierRegistrationService supplierRegistrationService)
        {
            this.supplierRegistrationService = supplierRegistrationService;
        }
        public IActionResult Index()
        {
            var model = this.supplierRegistrationService.GetAllQuestionByModule(1);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(SupplierRegistration supplierRegistration)
        {

            return View();
        }

        public IActionResult GetInternalQuestionaire()
        {
            SupplierRegistrationInternalQuestionViewModel model = new SupplierRegistrationInternalQuestionViewModel();
            return View("InternalQuestionare", model);
        }
        public IActionResult SyncSAP()
        {
            SyncSAPViewModel model = new SyncSAPViewModel();
            return View("SyncSAP", model);
        }
    }
}

Controllers/SupplierRequestController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WrokFlowWeb.Database;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel;
using WrokFlowWeb.ViewModel.SupplierRequest;
using static WrokFlowWeb.Constants.Constants;

namespace WrokFlowWeb.Controllers
{

    [Authorize]
    public class SupplierRequestController : Controller
    {
        private readonly ISupplierRequestService supplierRequest;
        private readonly ICategoryMasterService categoryService;

        public SupplierRequestController(ISupplierRequestService supplierRequest,ICategoryMasterService categoryMasterService)
        {
            this.supplierRequest = supplierRequest;
            this.categoryService = categoryMasterService;
        }
        public async Task<IActionResult> Index()
        {
           var result = await this.supplierRequest.GetSupplierRequests();
            return View();
        }

        public async Task<IActionResult> Get()
        {
            var model = new SupplierViewModel
            {
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
            };
            return View("Create", model);
        }

        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            var user = this.User.Identity.Name;
            supplierViewModel.CreatedBy = user;
            var result =  await this.supplierRequest.Add(supplierViewModel);
            return RedirectToAction("List", new { requestid = result });
        }

        public async Task<IActionResult> List(long requestid)
        {

            var model = new SupplierRequestListViewModel()
            {
                SupplierRequestId = requestid,
                SupplierRequests = await supplierRequest.GetSupplierRequests()
            };
            return View("List", model);
        }


        [HttpGet]
        public  Task<IActionResult> Details(long requestid)
        {

            return Edit(requestid);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(long requestid)
        {
            var response = await this.supplierRequest.GetSupplierRequest(requestid);
            var model = await bindSupplierViewModel(response);
            var ids = response.SupplierRequestCategoryMapping.Select(x => x.CategoryMasterId).ToList();
            model.CategoryMaster.Where(c => ids.Contains(c.CategoryMasterId)).ToList().ForEach(option=> {
                option.IsSelected = true;
            });

            return View("Edit", model);
        }


        async Task<SupplierViewModel> bindSupplierViewModel(SupplierRequest response)
        {
            
            var model = new SupplierViewModel()
            {
                SupplierRequestId = response.SupplierRequestId,
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
                SuplierTypeRequestId = response.SuplierTypeRequestId,
                RequestTypeMasterId = response.RequestTypeMasterId,
                RequesterName = response.RequesterName,
                Department = response.Department,
                SupplierName = response.SupplierName,
                Street = response.Street,
                Address1 = response.Address1,
                Address2 = response.Address2,
                City = response.City,
                PostalCode = response.PostalCode,
                Country = response.Country,
                FirstName = response.FirstName,
                LastName = response.LastName,
                EmailId = response.EmailId,
                ContactPhone = response.ContactPhone,
                CategoryMasterNames = string.Join(',',response.SupplierRequestCategoryMapping.Select(x=>x.CategoryMaster.Category).ToList())
            };
            return model;
        }

        [HttpGet]
        public async Task<IActionResult> InboxList()
        {
          List<InboxListViewModel> model  = this.supplierRequest.GetInboxList(this.User.Identity.Name);
          return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Approve(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                     model.SupplierViewModel = await bindSupplierViewModel(response);
                     model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> ViewApprovals(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                IsView = true,
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                    model.SupplierViewModel = await bindSupplierViewModel(response);
                    model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpPost]
        public async Task<IActionResult> Approve(RequestApprovalViewModel requestApprovalViewModel)
        {
            await this.supplierRequest.ApproveUpdate(requestApprovalViewModel, this.User.Identity.Name);

           return RedirectToAction("InboxList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryList(string search)
        {
            var model = await this.categoryService.GetAllCategories();
            model = !string.IsNullOrEmpty(search) ? model.Where(x=>x.Category.ToLower().Contains(search.ToLower()) ||  x.Description.ToLower().Contains(search.ToLower())).ToList(): model;
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_CategoryList", model);

            return View("CategoryList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryEdit(int categoryMasterid)
        {
            return RedirectToAction("CategoryEdit", "master", new { categoryId = categoryMasterid });
        }
    }
}  

Views/SupplierRegistration/Index.cshtml
@model WrokFlowWeb.ViewModel.SupplierRegistration.SupplierRegistration;

@{
    ViewBag.PageName = "Supplier Registration Request";
}@{
    ViewBag.Title = "Supplier Registration Request";
}

@using (Html.BeginForm("Create", "SupplierRegistration", FormMethod.Post))
{
    <div class="form-group">
        <label asp-for="SupplierRequestId"></label>
        <select class="form-control" asp-for="SupplierRequestId"
                asp-items="@(new SelectList(Model.SuppilerListViewModels,"SupplierRequestId","SupplierName"))">
            <option></option>
        </select>
        <span asp-validation-for="SupplierRequestId" class="text-danger"></span>
    </div>
    <button id="btnSubmit" type="submit" class="btn btn-primary">Invite</button>

    <h4>Question Preview</h4>

    for (int i = 0; i < Model.TabNames.Count(); i++)
    {
        <table>
            <h4>
                @Html.DisplayFor(model => model.TabNames[i].Tabname)
                @Html.HiddenFor(m => m.TabNames[i].TabId)
            </h4>
            @for (int qstNo = 0; qstNo < Model.TabNames[i].Questions.Count(); qstNo++)
            {
        <tr>
            @if (Model.TabNames[i].Questions[qstNo].QuestionControlType.ToString() == "Textbox")
            {
                @Html.HiddenFor(m => m.TabNames[i].Questions[qstNo].QuestionMasterId)
                <td>
                    @Html.DisplayFor(model => model.TabNames[i].Questions[qstNo].QuestionText)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.TabNames[i].Questions[qstNo].QuestionAnswer)
                </td>
            }
            @if (Model.TabNames[i].Questions[qstNo].QuestionControlType.ToString() == "MultiLineTextox")
            {
                @Html.HiddenFor(m => m.TabNames[i].Questions[qstNo].QuestionMasterId)
                <td>
                    @Html.DisplayFor(model => model.TabNames[i].Questions[qstNo].QuestionText)
                </td>
                <td>
                    @Html.TextAreaFor(model => model.TabNames[i].Questions[qstNo].QuestionAnswer)
                </td>
            }
            @if (Model.TabNames[i].Questions[qstNo].QuestionControlType.ToString() == "Dropdown")
            {
                @Html.HiddenFor(m => m.TabNames[i].Questions[qstNo].QuestionMasterId)
                <td>
                    @Html.DisplayFor(model => model.TabNames[i].Questions[qstNo].QuestionText)
                </td>
                <td>
                    @Html.DropDownListFor(model => model.TabNames[i].Questions[qstNo].SelectedValue, new SelectList(Model.TabNames[i].Questions[qstNo].DataSource, "Id", "Text", Model.TabNames[i].Questions[qstNo].SelectedValue), "Select")
                </td>
            }
        </tr>
            }
        </table>



    }


}

Views/SupplierRegistration/InternalQuestionare.cshtml
@model WrokFlowWeb.ViewModel.SupplierRegistration.SupplierRegistrationInternalQuestionViewModel

@{
    ViewBag.PageName = "Internal Questionaire";
}@{
    ViewBag.Title = "Create Internal Questionaire";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2 border-bottom">
            <a class="btn btn-primary ml-1" asp-action="List" asp-controller="SupplierRequest">Supplier Request List</a>
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 pt-10">
            <div class="d-inline-block two-column-form">
                <form asp-controller="SupplierRequest" asp-action="Create" method="post">
                    <div class="form-group">
                        <label asp-for="SupplierRequestId"></label>
                        <input asp-for="SupplierRequestId" class="form-control" />
                        <span asp-validation-for="SupplierRequestId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AccountGroup"></label>
                        <input asp-for="AccountGroup" class="form-control" />
                        <span asp-validation-for="AccountGroup" class="text-danger"></span>
                    </div>

                    <div class="form-group controlId">
                        <label asp-for="SearchTerm"></label>
                        <input asp-for="SearchTerm" class="form-control" />
                        <span asp-validation-for="SearchTerm" class="text-danger"></span>
                    </div>
                    <div class="form-group controlId">
                        <label asp-for="Industry"></label>
                        <input asp-for="Industry" class="form-control" />
                        <span asp-validation-for="Industry" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="TrainStation"></label>
                        <input asp-for="TrainStation" class="form-control" />
                        <span asp-validation-for="TrainStation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ActualQmsystem"></label>
                        <input asp-for="ActualQmsystem" class="form-control" />
                        <span asp-validation-for="ActualQmsystem" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ReconsiliationAccount"></label>
                        <input asp-for="ReconsiliationAccount" class="form-control" />
                        <span asp-validation-for="ReconsiliationAccount" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CashMangementGroup"></label>
                        <input asp-for="CashMangementGroup" class="form-control" />
                        <span asp-validation-for="CashMangementGroup" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CompanyCode"></label>
                        <input asp-for="CompanyCode" class="form-control" />
                        <span asp-validation-for="CompanyCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PaymentTerm"></label>
                        <input asp-for="PaymentTerm" class="form-control" />
                        <span asp-validation-for="PaymentTerm" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CheckDoubleInvoice"></label>
                        <select class="form-control" asp-for="CheckDoubleInvoice">
                            <option></option>
                            <option>Yes</option>
                            <option>No</option>
                        </select>
                        <span asp-validation-for="CheckDoubleInvoice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PaymentMethod"></label>
                        <input asp-for="PaymentMethod" class="form-control" />
                        <span asp-validation-for="PaymentMethod" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ClerkAbbrevation"></label>
                        <input asp-for="ClerkAbbrevation" class="form-control" />
                        <span asp-validation-for="ClerkAbbrevation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PurchasingOrganisation"></label>
                        <input asp-for="PurchasingOrganisation" class="form-control" />
                        <span asp-validation-for="PurchasingOrganisation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="OrderCurreny"></label>
                        <input asp-for="OrderCurreny" class="form-control" />
                        <span asp-validation-for="OrderCurreny" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SetIncoterm"></label>
                        <select class="form-control" asp-for="SetIncoterm">
                            <option></option>
                            <option>Yes</option>
                            <option>No</option>
                        </select>
                        <span asp-validation-for="SetIncoterm" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BlockForCompanyCodeAlba"></label>
                        <select class="form-control" asp-for="BlockForCompanyCodeAlba">
                            <option></option>
                            <option>Yes</option>
                            <option>No</option>
                        </select>
                        <span asp-validation-for="BlockForCompanyCodeAlba" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BlockForPurchasingOrganisation"></label>
                        <select class="form-control" asp-for="BlockForPurchasingOrganisation">
                            <option></option>
                            <option>Yes</option>
                            <option>No</option>
                        </select>
                        <span asp-validation-for="BlockForPurchasingOrganisation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BlockForQualityReasons"></label>
                        <input asp-for="BlockForQualityReasons" class="form-control" />
                        <span asp-validation-for="BlockForQualityReasons" class="text-danger"></span>
                    </div>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Create Internal Questionnaire</button>
                    <a asp-controller="SupplierRequest" asp-action="List" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
            $(".controlId").hide();
            $(".error").hide();
            $("#RequestTypeMasterId").on("change", function () {
                if ($("#RequestTypeMasterId option:selected").val() == 2) {
                    $(".controlId").show();
                } else {
                    $(".controlId").hide();
                }
            });
    </script>
    <script type="text/javascript">
            $(function () {
                $("#btnSubmit").click(function () {
                    var checked_checkboxes = $("#tblCategory input[type=checkbox]:checked");
                    if (checked_checkboxes.length == 0) {
                        $(".error").show();
                        return false;
                    } else {
                        $(".error").hide();
                        return true;
                    }

                });
            });
    </script>
}

Views/SupplierRegistration/SyncSAP.cshtml
@model WrokFlowWeb.ViewModel.SupplierRegistration.SyncSAPViewModel

@{
    ViewBag.PageName = "Sync SAP";
}@{
    ViewBag.Title = "Sync SAP";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2 border-bottom">
            @*<a class="btn btn-primary ml-1" asp-action="List" asp-controller="SupplierRequest">Supplier Request List</a>*@
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 pt-10">
            <div class="d-inline-block two-column-form">
                <form asp-controller="SupplierRequest" asp-action="Create" method="post">
                    <div class="form-group">
                        <label asp-for="SupplierRequestId"></label>
                        <input asp-for="SupplierRequestId" class="form-control" />
                        <span asp-validation-for="SupplierRequestId" class="text-danger"></span>
                    </div>
                   
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Sync SAP</button>
                    <a asp-controller="SupplierRequest" asp-action="List" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
            $(".controlId").hide();
            $(".error").hide();
            $("#RequestTypeMasterId").on("change", function () {
                if ($("#RequestTypeMasterId option:selected").val() == 2) {
                    $(".controlId").show();
                } else {
                    $(".controlId").hide();
                }
            });
    </script>
    <script type="text/javascript">
            $(function () {
                $("#btnSubmit").click(function () {
                    var checked_checkboxes = $("#tblCategory input[type=checkbox]:checked");
                    if (checked_checkboxes.length == 0) {
                        $(".error").show();
                        return false;
                    } else {
                        $(".error").hide();
                        return true;
                    }

                });
            });
    </script>
}