Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.IIS.Core;
using WrokFlowWeb.Areas.Identity.Data;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel;
using WrokFlowWeb.ViewModel.Role;

namespace WrokFlowWeb.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<WrokFlowWebUser> userManager;
        private readonly ISupplierRequestService supplierRequest;

        public RoleController(RoleManager<IdentityRole> roleManager,
                              UserManager<WrokFlowWebUser> userManager,
                              ISupplierRequestService supplierRequest)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.supplierRequest = supplierRequest;
        }
        // GET: RoleController
        public ActionResult ListRoles()
        {
            return View(roleManager.Roles);
        }

        public ActionResult ListUsers(String search)
        {
            var result = this.supplierRequest.GetAllUsers(search).Result;
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_IndexGrid", result);

            return View();
        }

        // GET: RoleController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel()
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View("Edit", model);
        }

        // GET: RoleController/Details/5
        public async Task<IActionResult> GetUserDetails(string id)
        {
            //supplierRequest.getuser

            //return View("Edit",model);
            return null;
        }

        // GET: RoleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole()
                {
                    Name = roleViewModel.RoleName
                };
                IdentityResult identityResult = await roleManager.CreateAsync(identityRole);
                if (identityResult.Succeeded)
                {
                    return RedirectToAction(nameof(ListRoles));
                }

                foreach (IdentityError error in identityResult.Errors)
                {
                    ModelState.AddModelError("",error.Description);
                }
            }
            return View(roleViewModel);

        }

        // GET: RoleController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RoleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditRoleViewModel editRoleViewModel)
        {
            var role = await roleManager.FindByIdAsync(editRoleViewModel.Id);
            if (role == null) {
                ViewBag.ErrorMessage = $"Role with Id = {editRoleViewModel.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = editRoleViewModel.RoleName;
                var result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(ListRoles));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty,error.Description);
                }
            }

          

            return View(editRoleViewModel);
        }

        // GET: RoleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RoleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleid)
        {
            var role = await roleManager.FindByIdAsync(roleid);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleid} cannot be found";
                return View("NotFound");
            }

            var model = new UserRoleViewModel() { 
                RoleId = roleid
            };
            

            foreach (var user in userManager.Users.Where(x=>x.UserType==1).ToList())
            {
                var userRoleViewModel = new UserRoleList()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                model.UserRoleList.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(UserRoleViewModel userRoleViewModel)
        {
            var role = await roleManager.FindByIdAsync(userRoleViewModel.RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {userRoleViewModel.RoleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < userRoleViewModel.UserRoleList.Count; i++)
            {
                var user = await userManager.FindByIdAsync(userRoleViewModel.UserRoleList[i].UserId);
                IdentityResult identityResult = null;
                if (userRoleViewModel.UserRoleList[i].IsSelected &&  !(await userManager.IsInRoleAsync(user,role.Name)))
                {
                    identityResult = await userManager.AddToRoleAsync(user,role.Name);
                }else if (!userRoleViewModel.UserRoleList[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    identityResult = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }
                if (identityResult.Succeeded) {
                    if (i< (userRoleViewModel.UserRoleList.Count-1))
                    {
                        continue;
                    }
                    else
                    {
                        return RedirectToAction("Details", new { id = userRoleViewModel.RoleId });
                    }
                }
            }
            return RedirectToAction("Details", new { id = userRoleViewModel.RoleId });
        }

        [HttpGet]
        public async Task<IActionResult> MapUserSupplier()
        {
            var model = await this.supplierRequest.GetSUpplierUserMappingViewModel();
            return View("UserSupplierMap", model);
        }

        [HttpPost]
        public async Task<IActionResult> PostMapUserSupplier(SupplierUserMappingViewModel supplierUserMappingViewModel)
        {
            await this.supplierRequest.PostMapUserSupplier(supplierUserMappingViewModel,"");
            return RedirectToAction("ListUsers");
        }
    }
}

Controllers/SupplierRequestController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WrokFlowWeb.Database;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel;
using WrokFlowWeb.ViewModel.SupplierRequest;
using static WrokFlowWeb.Constants.Constants;

namespace WrokFlowWeb.Controllers
{

    [Authorize]
    public class SupplierRequestController : Controller
    {
        private readonly ISupplierRequestService supplierRequest;
        private readonly ICategoryMasterService categoryService;

        public SupplierRequestController(ISupplierRequestService supplierRequest,ICategoryMasterService categoryMasterService)
        {
            this.supplierRequest = supplierRequest;
            this.categoryService = categoryMasterService;
        }
        public async Task<IActionResult> Index()
        {
           var result = await this.supplierRequest.GetSupplierRequests();
            return View();
        }

        public async Task<IActionResult> Get()
        {
            var model = new SupplierViewModel
            {
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
            };
            return View("Create", model);
        }

        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            var user = this.User.Identity.Name;
            supplierViewModel.CreatedBy = user;
            var result =  await this.supplierRequest.Add(supplierViewModel);
            return RedirectToAction("List", new { requestid = result });
        }

        public async Task<IActionResult> List(long requestid)
        {

            var model = new SupplierRequestListViewModel()
            {
                SupplierRequestId = requestid,
                SupplierRequests = await supplierRequest.GetSupplierRequests()
            };
            return View("List", model);
        }


        [HttpGet]
        public  Task<IActionResult> Details(long requestid)
        {

            return Edit(requestid);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(long requestid)
        {
            var response = await this.supplierRequest.GetSupplierRequest(requestid);
            var model = await bindSupplierViewModel(response);
            var ids = response.SupplierRequestCategoryMapping.Select(x => x.CategoryMasterId).ToList();
            model.CategoryMaster.Where(c => ids.Contains(c.CategoryMasterId)).ToList().ForEach(option=> {
                option.IsSelected = true;
            });

            return View("Edit", model);
        }


        async Task<SupplierViewModel> bindSupplierViewModel(SupplierRequest response)
        {
            
            var model = new SupplierViewModel()
            {
                SupplierRequestId = response.SupplierRequestId,
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
                SuplierTypeRequestId = response.SuplierTypeRequestId,
                RequestTypeMasterId = response.RequestTypeMasterId,
                RequesterName = response.RequesterName,
                Department = response.Department,
                SupplierName = response.SupplierName,
                Street = response.Street,
                Address1 = response.Address1,
                Address2 = response.Address2,
                City = response.City,
                PostalCode = response.PostalCode,
                Country = response.Country,
                FirstName = response.FirstName,
                LastName = response.LastName,
                EmailId = response.EmailId,
                ContactPhone = response.ContactPhone,
                CategoryMasterNames = string.Join(',',response.SupplierRequestCategoryMapping.Select(x=>x.CategoryMaster.Category).ToList())
            };
            return model;
        }

        [HttpGet]
        public async Task<IActionResult> InboxList()
        {
          List<InboxListViewModel> model  = this.supplierRequest.GetInboxList(this.User.Identity.Name);
          return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Approve(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                     model.SupplierViewModel = await bindSupplierViewModel(response);
                     model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> ViewApprovals(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                IsView = true,
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                    model.SupplierViewModel = await bindSupplierViewModel(response);
                    model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpPost]
        public async Task<IActionResult> Approve(RequestApprovalViewModel requestApprovalViewModel)
        {
            await this.supplierRequest.ApproveUpdate(requestApprovalViewModel, this.User.Identity.Name);

           return RedirectToAction("InboxList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryList(string search)
        {
            var model = await this.categoryService.GetAllCategories();
            model = !string.IsNullOrEmpty(search) ? model.Where(x=>x.Category.ToLower().Contains(search.ToLower()) ||  x.Description.ToLower().Contains(search.ToLower())).ToList(): model;
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_CategoryList", model);

            return View("CategoryList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryEdit(int categoryMasterid)
        {
            return RedirectToAction("CategoryEdit", "master", new { categoryId = categoryMasterid });
        }
    }
}  

Views/SupplierRequest/CategoryList.cshtml
@model IEnumerable<WrokFlowWeb.ViewModel.CategoryMaster.CategoryMasterViewModel>
@{
    ViewBag.Title = "Category Listing";
}
@{
    ViewBag.PageName = "Masters";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-between pb-2">
            <div class="search form-group mb-0">
                <input class="form-control" id="GridSearch" placeholder="search" />
            </div>
            <div>
                <a class="btn btn-primary ml-1" asp-controller="master" asp-action="CategoryCreate"> Add New Category</a>
            </div>
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 grid">
            @Html.AjaxGrid(Url.Action("CategoryList"))
        </div>
    </div>
</div>

<script>
    document.getElementById("GridSearch").addEventListener("input", function () {
        const grid = new MvcGrid(document.querySelector(".mvc-grid"));


        grid.url.searchParams.set("search", this.value);

        grid.reload();
    });
</script>

Views/SupplierRequest/Edit.cshtml
@model WrokFlowWeb.ViewModel.SupplierViewModel


@{
    ViewBag.Title = "Edit Supplier Request";
}

@{
    ViewBag.PageName = "ListUsers";
}


<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2 border-bottom">
            <a class="btn btn-primary ml-1" asp-action="ListUsers" asp-controller="Role">All Users</a>
            <a class="btn btn-primary ml-1" asp-controller="role" asp-action="MapUserSupplier"> Map User Supplier</a>
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 pt-10">
            <div class="d-inline-block two-column-form">
                <form asp-controller="SupplierRequest" asp-action="Create" method="post">
                    <div class="form-group">
                        <label asp-for="SuplierTypeRequestId"></label>
                        <select class="form-control" asp-for="SuplierTypeRequestId"
                                asp-items="@(new SelectList(Model.SuplierTypeRequest,"SuplierTypeRequestId","SuplierTypeRequest"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="SuplierTypeRequestId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RequestTypeMasterId"></label>
                        <select class="form-control" asp-for="RequestTypeMasterId"
                                asp-items="@(new SelectList(Model.RequestTypeMaster,"RequestTypeMasterId","RequestType"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="RequestTypeMasterId" class="text-danger"></span>
                    </div>

                    <div class="form-group controlId">
                        <label asp-for="RequesterName"></label>
                        <input asp-for="RequesterName" class="form-control" />
                        <span asp-validation-for="RequesterName" class="text-danger"></span>

                    </div>
                    <div class="form-group controlId">
                        <label asp-for="Department"></label>
                        <input asp-for="Department" class="form-control" />
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SupplierName"></label>
                        <input asp-for="SupplierName" class="form-control" />
                        <span asp-validation-for="SupplierName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Street"></label>
                        <input asp-for="Street" class="form-control" />
                        <span asp-validation-for="Street" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address1"></label>
                        <input asp-for="Address1" class="form-control" />
                        <span asp-validation-for="Address1" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address2"></label>
                        <input asp-for="Address2" class="form-control" />
                        <span asp-validation-for="Address2" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PostalCode"></label>
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmailId"></label>
                        <input asp-for="EmailId" class="form-control" />
                        <span asp-validation-for="EmailId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactPhone"></label>
                        <input asp-for="ContactPhone" class="form-control" />
                        <span asp-validation-for="ContactPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryMaster"></label>
                        <table id="tblCategory">
                            @for (int i = 0; i < Model.CategoryMaster.Count(); i++)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(m => m.CategoryMaster[i].IsSelected)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => m.CategoryMaster[i].Category)
                                        @Html.HiddenFor(m => m.CategoryMaster[i].CategoryMasterId)
                                        @Html.HiddenFor(m => m.CategoryMaster[i].Category)
                                    </td>
                                </tr>
                            }
                        </table>
                        <span class="error">Please select at-least one category.</span>
                        <br />
                        <br />
                    </div>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Update Supplier Request</button>
                    <a asp-controller="SupplierRequest" asp-action="List" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        $(document).ready(function () {
            if ($("#RequestTypeMasterId option:selected").val() == 2) {
                $(".controlId").show();
            } else {
                $(".controlId").hide();
            }
        });
        //$("#controlId").hide();
        $(".error").hide();
        $("#RequestTypeMasterId").on("change", function () {
            if ($("#RequestTypeMasterId option:selected").val() == 2) {
                $(".controlId").show();
            } else {
                $(".controlId").hide();
            }
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#btnSubmit").click(function () {
                var checked_checkboxes = $("#tblCategory input[type=checkbox]:checked");
                if (checked_checkboxes.length == 0) {
                    $(".error").show();
                    return false;
                } else {
                    $(".error").hide();
                    return true;
                }

            });
        });
    </script>
}

Views/SupplierRequest/InboxList.cshtml
@model List<WrokFlowWeb.ViewModel.InboxListViewModel>
@{
    ViewBag.PageName = "Inbox";
}

@{
    ViewBag.Title = "Inbox Items";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="w-100 h-100 grid-h-100 mvc-grid">
        @(Html
        .Grid(Model)
        .Build(columns =>
        {
            columns.Add(model => model.ModuleName).Titled("Module");
            columns.Add(model => model.RequestId).Titled("Request");
            columns.Add(model => $"<a class=\"btn btn-sm btn-warning whiteColor\" href=\"Approve?requestid={model.RequestId}&moduleid={model.ModuleId}\">Aprrove/Reject</a>").Encoded(false).Css("w-122"); ;

        })
         .Empty("No request for approval")
        .Pageable(pager =>
        {
            pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 10, "10" }, { 25, "25" } };
            pager.ShowPageSizes = true;
            pager.PagesToDisplay = 3;
            pager.CurrentPage = 1;
            pager.RowsPerPage = 10;
        })
        )
    </div>
</div>

Views/SupplierRequest/List.cshtml
@model WrokFlowWeb.ViewModel.SupplierRequest.SupplierRequestListViewModel
@{
    ViewBag.Title = "Supplier Requests";
}
@{
    ViewBag.PageName = "SupplierRequest";
}


<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2">
            <a class="btn btn-primary" asp-action="Get" asp-controller="SupplierRequest"> Add Supplier Request</a>
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 grid-h-100 mvc-grid">
            @(Html
    .Grid(Model.SupplierRequests)
    .Build(columns =>
    {
        columns.Add(model => model.SupplierRequestId).Titled("Supplier Code");
        columns.Add(model => model.SuplierTypeRequest.SuplierTypeRequest).Titled("Suplier Type");
        columns.Add(model => model.RequestTypeMaster.RequestType).Titled("Request Type");
        columns.Add(model => model.RequesterName).Titled("Requester Name");
        columns.Add(model => model.SupplierName).Titled("Supplier Name");
        columns.Add(model => model.PostalCode).Titled("Postal Code");
        columns.Add(model => model.EmailId).Titled("Email");
        columns.Add(model => model.ContactPhone).Titled("Contact No");
        columns.Add(model => model.IsRejected ? "Rejected" : model.SupplierRequestApprovalId > 0? model.SupplierRequestApprovalLog.Where(x=>  x.SupplierRequestApprovalId==model.SupplierRequestApprovalId).FirstOrDefault().RoleApprovalMaster.Role.Name: "Approved").Titled("Approval Status");

        columns.Add(model => string.Join(',',model.SupplierRequestCategoryMapping.Select(y=>y.CategoryMaster.Category))).Titled("Category");
        columns.Add(model => !model.IsEditable.GetValueOrDefault()? $"<a class=\"btn btn-sm btn-warning whiteColor\" href=\"ViewApprovals?requestid={model.SupplierRequestId}&moduleid=1\"><i class=\"fa fa-eye\"></i>&nbsp;View Approvals</a>" : $"<a class=\"btn btn-sm btn-info whiteColor\" href=\"Edit?requestid={model.SupplierRequestId}\"><i class=\"fa fa-pencil-alt\"></i>&nbsp;Edit</a>").Encoded(false).Css("text-right");
        //columns.Add(model => $"<a href=\"@Url.Action('Delete', 'movies', new { requestid = model.SupplierRequestId })\">Edit</a>").Encoded(false);

    })
     .Empty("No supplier request data to be displayed")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 10, "10" }, { 25, "25" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 3;
        pager.CurrentPage = 1;
        pager.RowsPerPage = 4;
    })
)
        </div>
     </div>
</div>
    


    

Views/SupplierRequest/_CategoryList.cshtml
@model IEnumerable<WrokFlowWeb.ViewModel.CategoryMaster.CategoryMasterViewModel>


@(Html
    .Grid(Model)
    .Build(columns =>
    {
        
        columns.Add(model => model.Category).Titled("Category");
        columns.Add(model => model.Description).Titled("Description");
        columns.Add(model => $"<a href=\"CategoryEdit?categoryMasterid={model.CategoryMasterId}\">Edit</a>").Encoded(false);

    })
    .Empty("No categories to be displayed")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 10, "10" }, { 25, "25" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 3;
        pager.CurrentPage = 1;
        pager.RowsPerPage = 10;
    })
)