Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel.Question;

namespace WrokFlowWeb.Controllers
{
    public class QuestionController : Controller
    {
        private readonly ISupplierRegistrationService supplierRegistrationService;

        public QuestionController(ISupplierRegistrationService supplierRegistrationService)
        {
            this.supplierRegistrationService = supplierRegistrationService;
        }

        public IActionResult Index()
        {
            var model = this.supplierRegistrationService.GetQuestionMasterViewModel();
            return View("CreateQuestion", model);
        }

        [HttpPost]
        public IActionResult Create(QuestionMasterViewModel questionMasterViewModel)
        {
            this.supplierRegistrationService.AddQuestionMaster(questionMasterViewModel);
            var responseModel =  this.supplierRegistrationService.GetAllQuestions();
            return View("QuestionList", responseModel);
        }

        [HttpGet]
        public IActionResult List()
        {
            var responseModel = this.supplierRegistrationService.GetAllQuestions();
            return View("QuestionList", responseModel);
        }

        [HttpGet]
        public JsonResult LoadTab(int moduleId)
        {
            var responseModel = this.supplierRegistrationService.LoadTabDetails(moduleId);
            return Json(responseModel);
        }

        [HttpGet]
        public JsonResult CheckLoadDataSource(int controlId)
        {
            var responseModel = this.supplierRegistrationService.CheckLoadDataSource(controlId);
            return Json(responseModel);
        }
    }
}

Controllers/SupplierRequestController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WrokFlowWeb.Database;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel;
using WrokFlowWeb.ViewModel.SupplierRequest;
using static WrokFlowWeb.Constants.Constants;

namespace WrokFlowWeb.Controllers
{

    [Authorize]
    public class SupplierRequestController : Controller
    {
        private readonly ISupplierRequestService supplierRequest;
        private readonly ICategoryMasterService categoryService;

        public SupplierRequestController(ISupplierRequestService supplierRequest,ICategoryMasterService categoryMasterService)
        {
            this.supplierRequest = supplierRequest;
            this.categoryService = categoryMasterService;
        }
        public async Task<IActionResult> Index()
        {
           var result = await this.supplierRequest.GetSupplierRequests();
            return View();
        }

        public async Task<IActionResult> Get()
        {
            var model = new SupplierViewModel
            {
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
            };
            return View("Create", model);
        }

        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            var user = this.User.Identity.Name;
            supplierViewModel.CreatedBy = user;
            var result =  await this.supplierRequest.Add(supplierViewModel);
            return RedirectToAction("List", new { requestid = result });
        }

        public async Task<IActionResult> List(long requestid)
        {

            var model = new SupplierRequestListViewModel()
            {
                SupplierRequestId = requestid,
                SupplierRequests = await supplierRequest.GetSupplierRequests()
            };
            return View("List", model);
        }


        [HttpGet]
        public  Task<IActionResult> Details(long requestid)
        {

            return Edit(requestid);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(long requestid)
        {
            var response = await this.supplierRequest.GetSupplierRequest(requestid);
            var model = await bindSupplierViewModel(response);
            var ids = response.SupplierRequestCategoryMapping.Select(x => x.CategoryMasterId).ToList();
            model.CategoryMaster.Where(c => ids.Contains(c.CategoryMasterId)).ToList().ForEach(option=> {
                option.IsSelected = true;
            });

            return View("Edit", model);
        }


        async Task<SupplierViewModel> bindSupplierViewModel(SupplierRequest response)
        {
            
            var model = new SupplierViewModel()
            {
                SupplierRequestId = response.SupplierRequestId,
                SuplierTypeRequest = await this.supplierRequest.GetSupplierTypeRequestMaster(),
                RequestTypeMaster = await this.supplierRequest.GetRequestTypeMaster(),
                CategoryMaster = await this.supplierRequest.GetCategoryMaster(),
                SuplierTypeRequestId = response.SuplierTypeRequestId,
                RequestTypeMasterId = response.RequestTypeMasterId,
                RequesterName = response.RequesterName,
                Department = response.Department,
                SupplierName = response.SupplierName,
                Street = response.Street,
                Address1 = response.Address1,
                Address2 = response.Address2,
                City = response.City,
                PostalCode = response.PostalCode,
                Country = response.Country,
                FirstName = response.FirstName,
                LastName = response.LastName,
                EmailId = response.EmailId,
                ContactPhone = response.ContactPhone,
                CategoryMasterNames = string.Join(',',response.SupplierRequestCategoryMapping.Select(x=>x.CategoryMaster.Category).ToList())
            };
            return model;
        }

        [HttpGet]
        public async Task<IActionResult> InboxList()
        {
          List<InboxListViewModel> model  = this.supplierRequest.GetInboxList(this.User.Identity.Name);
          return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Approve(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                     model.SupplierViewModel = await bindSupplierViewModel(response);
                     model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> ViewApprovals(long requestid, long moduleid)
        {
            RequestApprovalViewModel model = new RequestApprovalViewModel
            {
                IsView = true,
                InboxListViewModel = new InboxListViewModel()
                {
                    RequestId = requestid,
                    ModuleId = moduleid
                }
            };
            switch (moduleid)
            {
                case (long)Module.SupplierRequest:
                    var response = await this.supplierRequest.GetSupplierRequest(requestid);
                    model.SupplierViewModel = await bindSupplierViewModel(response);
                    model.SupplierRequestApprovalLog = await this.supplierRequest.GetApprovedLogBySupplierRequestId(requestid);
                    return View("SupplierApproveView", model);
                default:
                    break;
            }

            return null;
        }

        [HttpPost]
        public async Task<IActionResult> Approve(RequestApprovalViewModel requestApprovalViewModel)
        {
            await this.supplierRequest.ApproveUpdate(requestApprovalViewModel, this.User.Identity.Name);

           return RedirectToAction("InboxList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryList(string search)
        {
            var model = await this.categoryService.GetAllCategories();
            model = !string.IsNullOrEmpty(search) ? model.Where(x=>x.Category.ToLower().Contains(search.ToLower()) ||  x.Description.ToLower().Contains(search.ToLower())).ToList(): model;
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_CategoryList", model);

            return View("CategoryList");
        }

        [HttpGet]
        public async Task<IActionResult> CategoryEdit(int categoryMasterid)
        {
            return RedirectToAction("CategoryEdit", "master", new { categoryId = categoryMasterid });
        }
    }
}  

Views/Question/CreateQuestion.cshtml
@model WrokFlowWeb.ViewModel.Question.QuestionMasterViewModel

@{
    ViewBag.PageName = "Question Master";
}@{
    ViewBag.Title = "Create Question Master";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2 border-bottom">
            @*<a class="btn btn-primary ml-1" asp-action="List" asp-controller="SupplierRequest">Supplier Request List</a>*@
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 pt-10">
            <div class="d-inline-block two-column-form">
                <form asp-controller="Question" asp-action="Create" method="post">
                    <div class="form-group">
                        <label asp-for="ApprovalFormMasterId"></label>
                        <select class="form-control" asp-for="ApprovalFormMasterId"
                                asp-items="@(new SelectList(Model.ApprovalFormMaster,"ApprovalFormMasterId","ApprovalFormMasterName"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="ApprovalFormMasterId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TabMasterId"></label>
                        <select class="form-control" asp-for="TabMasterId"
                                asp-items="@(new SelectList(Model.TabMasterSource,"TabMasterId","TabMasterName"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="TabMasterId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ControlMasterId"></label>
                        <select class="form-control" asp-for="ControlMasterId"
                                asp-items="@(new SelectList(Model.ControlMaster,"ControlMasterId","ControlName"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="ControlMasterId" class="text-danger"></span>
                    </div>
                    <div class="form-group controlId">
                        <label asp-for="DataSourceMasterId"></label>
                        <select class="form-control" asp-for="DataSourceMasterId"
                                asp-items="@(new SelectList(Model.DataSourceMaster,"DataSourceMasterId","DataSourceName"))">
                            <option></option>
                        </select>
                        <span asp-validation-for="DataSourceMasterId" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="QuestionText"></label>
                        <input asp-for="QuestionText" class="form-control" />
                        <span asp-validation-for="QuestionText" class="text-danger"></span>
                    </div>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Create Question</button>
                    <a asp-controller="Question" asp-action="List" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
    $(function () {
        $("#ApprovalFormMasterId").on("change", function () {
            
            var categoryId = $(this).val();
            $("#TabMasterId").empty();
            $("#TabMasterId").append("<option>Loading...</option>");
            $.getJSON(`Question/LoadTab?moduleId=${categoryId}`, (data) => {
                $("#TabMasterId").empty();
                $("#TabMasterId").append("<option></option>");
                $.each(data, function (i, item) {
                    $("#TabMasterId").append(`<option value="${item.tabMasterId}">${item.tabMasterName}</option>`);
                });
            });
        });

        $("#ControlMasterId").on("change", function () {
            var categoryId = $(this).val();
            $(".controlId").hide();
            $.getJSON(`Question/CheckLoadDataSource?controlId=${categoryId}`, (data) => {
                debugger;
                if (data == true) {
                    $(".controlId").show();
                } else {
                    $(".controlId").hide();
                }
            });
        });
    });
    </script>
}

Views/Question/QuestionList.cshtml
@model IEnumerable<WrokFlowWeb.Database.QuestionMaster>
@{
        ViewBag.Title = "Question List";
    }
@{
        ViewBag.PageName = "Question List";
    }


<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex justify-content-end pb-2">
           <a class="btn btn-primary" asp-action="Index" asp-controller="Question"> Add Question</a>
        </div>
        <div class="d-flex flex-1 overflow-y w-100 h-100 grid-h-100">
            @(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.TabMaster.ApprovalFormMaster.ApprovalFormMasterName).Titled("Module");
        columns.Add(model => model.TabMaster.TabMasterName).Titled("Tab Name");
        columns.Add(model => model.ControlMaster.ControlName).Titled("Control Name");
        columns.Add(model => model.DataSourceMaster.DataSourceName).Titled("Data Source");
        columns.Add(model => model.QuestionText).Titled("Question");
    })
     .Empty("No questions added.")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 10, "10" }, { 25, "25" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 3;
        pager.CurrentPage = 1;
        pager.RowsPerPage = 10;
    })
)
        </div>
    </div>
</div>