Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WrokFlowWeb.Services.Interface;
using WrokFlowWeb.ViewModel.CategoryMaster;

namespace WrokFlowWeb.Controllers
{
    [Authorize]
    public class MasterController : Controller
    {
        public IMasterService MasterService { get; }

        public MasterController(IMasterService masterService)
        {
            MasterService = masterService;
        }
        
        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public IActionResult CategoryCreate()
        {
            CategoryMasterViewModel categoryMasterViewModel = new CategoryMasterViewModel();
            return View("CategoryCreate", categoryMasterViewModel);
        }

        public async Task<IActionResult> CreateCategory(CategoryMasterViewModel categoryMasterViewModel)
        {

            if (ModelState.IsValid)
            {
                if (await MasterService.AddCategory(categoryMasterViewModel) > 0)
                {
                    return RedirectToAction("CategoryList", "SupplierRequest");
                }
            }
            return View();
        }

        public async Task<IActionResult> CategoryEdit(int categoryId)
        {
            var response = await MasterService.GetCategoryById(categoryId);
            CategoryMasterViewModel categoryMasterViewModel = new CategoryMasterViewModel() { 
                 Category = response.Category,
                 CategoryMasterId = response.CategoryMasterId,
                 Description = response.Description
            };
            return View("CategoryEdit", categoryMasterViewModel);
        }

        public async Task<IActionResult> CategoryEditUpdate(CategoryMasterViewModel categoryMasterViewModel)
        {
            if (ModelState.IsValid)
            {
                await MasterService.UpdateCategory(categoryMasterViewModel);
               
            }
            return RedirectToAction("CategoryList", "SupplierRequest");
        }
    }
}

Views/Master/CategoryCreate.cshtml
@model WrokFlowWeb.ViewModel.CategoryMaster.CategoryMasterViewModel

@{
    ViewBag.Title = "Create Category";
}
@{
    ViewBag.PageName = "Masters";
}




<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex flex-1 w-100 h-100 overflow-y pt-10">
            <div class="single-column d-flex flex-column">
                <form method="post" asp-controller="Master" asp-action="CreateCategory">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Category"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Create Category</button>
                    <a asp-controller="SupplierRequest" asp-action="CategoryList" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>  
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Master/CategoryEdit.cshtml
@model WrokFlowWeb.ViewModel.CategoryMaster.CategoryMasterViewModel

@{
    ViewBag.Title = "Edit Category";
}
@{
    ViewBag.PageName = "Masters";
}

<div class="w-100 h-100 bg-white p-10 border-radius-5 box-shadow">
    <div class="d-flex flex-column h-100 w-100">
        <div class="d-flex flex-1 w-100 h-100 overflow-y pt-10">
            <div class="single-column d-flex flex-column">
                <form method="post" asp-controller="Master" asp-action="CategoryEditUpdate">
                    @Html.HiddenFor(m => m.CategoryMasterId)
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Category"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Update Category</button>
                    <a asp-controller="SupplierRequest" asp-action="CategoryList" class="btn btn-primary" style="width:auto">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}